# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ndB3aKucnV5AapFo0KoIet53gCSM6N_
"""

import matplotlib.pyplot as plt
 import  numpy as np
 x=np.array([0,8])
 y=np.array([0,360])
 plt.plot(x,y)
 plt.show()

import matplotlib.pyplot as plt
 import  numpy as np
 x=np.array([0,15])
 y=np.array([0,90])
 plt.plot(x,y)
 plt.show()

import matplotlib.pyplot as plt
 import  numpy as np
 x=np.array([5,8,6])
 y=np.array([3,5,8])
 plt.plot(x,y)
 plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 2, 4, 5, 7, 81])
y = np.array([0, 7, 6, 9, 2, 1])
mycolor = ['blue', 'red', 'purple', 'lime', 'green', 'yellow']  # Corrected 'puruple' to 'purple'
size = [20, 10, 12, 160, 45, 18]
plt.scatter(x, y, color=mycolor, s=size, alpha=0.3)
plt.show()

import matplotlib.pyplot as plt
 import  numpy as np
 x=np.array([610,23,611,23,610,23])
 y=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22])
 plt.plot(x,y)
 plt.show(gurh="610.23")

import matplotlib.pyplot as plt
 import  numpy as np
 x=np.array([35,20,25,15])
 mylabels=("Apples","Bananas","CHerries","Dates")
 plt.pie(x,labels=mylabels)
 plt.show()